### ISSUE TITLE
failed for aliases

### ISSUE THREAD

**Issue by IAD** [wawandco/fako#12]
Example:
`type DateTime string
`
Runtime error:
`panic serving 172.20.0.1:33258: reflect.Set: value of type string is not assignable to type DateTime
`

**Comment by paganotoni** [comment]
Hi @IAD thanks for reporting this one, i recently added a test scenario for that particular case:
https://github.com/wawandco/fako/blob/master/fako_test.go#L110
But it passes, may i be missing something ?
