### ISSUE TITLE
Nested Faking

### ISSUE THREAD

**Issue by paganotoni** [wawandco/fako#5]
Unsure if we need to add this, if you're reading this and thing it worth doing it, please let me know.
Appreciate your feedback!, i will add details on the implementation soon.

**Comment by hug-dev** [comment]
Hello :wave: 

I was actually looking for this :smile: 
I have a Go struct where its fields are other structs containing standard types (`bool`, `uint8`, etc). I am trying to apply `Fuzz` on it to generate a random struct value for testing.
It seems that currently it does not work but I need to do it for all the subtypes. Would be nice if the fuzzing worked recursively!

**Comment by hug-dev** [comment]
Ah noticed that `uint8` was not supported too :grimacing: 

edit: hmm I have just checked `gofuzz` and it seems to be doing exactly what I want. I guess what I wanted was more like fuzzing as opposed as generating fake data.
